require('dotenv').config();
const express = require('express');
const bodyParser = require('body-parser');
const cors = require('cors'); // Essential for React (Port 3000) to talk to Node (Port 3001)
const { spawn } = require('child_process');

const app = express();

// Enable Cross-Origin Resource Sharing (allows frontend to connect)
app.use(cors());
app.use(bodyParser.json());

// Health check
app.get('/_health', (req, res) => res.json({ status: 'ok' }));

// ---------------------------------------------------------
//  NEW LOGIC: DELEGATE TO PYTHON
// ---------------------------------------------------------
app.post('/api/kg/query', async (req, res) => {
  const { userQuestion } = req.body;

  if (!userQuestion) {
    return res.status(400).json({ error: 'userQuestion required' });
  }

  console.log(`📩 Handing over to Python: "${userQuestion}"`);

  // 1. Spawn the Python process
  // Make sure 'query_engine.py' is in the same folder as this server.js
  const pythonProcess = spawn('python', ['query_engine.py', userQuestion]);

  let dataString = '';
  let errorString = '';

  // 2. Collect data from Python's print() statements
  pythonProcess.stdout.on('data', (data) => {
    dataString += data.toString();
  });

  // 3. Collect any errors
  pythonProcess.stderr.on('data', (data) => {
    errorString += data.toString();
  });

  // 4. When Python finishes
  pythonProcess.on('close', (code) => {
    console.log(`Python finished with code ${code}`);

    if (code !== 0) {
      console.error("Python Error Details:", errorString);
      return res.status(500).json({ 
        error: "The Python script failed.", 
        details: errorString 
      });
    }

    try {
      // 5. Parse the JSON result from Python
      // Python should print exactly one valid JSON object
      const result = JSON.parse(dataString);
      
      // Send it back to React
      res.json({
        answer: result.answer,      // The main answer text
        cypher: result.cypher || "Generated by Python", 
        provenance: [],             // Optional
        confidence: "high"          // Optional
      });

    } catch (e) {
      console.error("Failed to parse JSON from Python:", dataString);
      res.status(500).json({ 
        error: "Invalid response from AI engine", 
        rawOutput: dataString 
      });
    }
  });
});

const port = process.env.PORT || 3002;
app.listen(port, () => console.log(`🚀 KG Manager running on port ${port}`));

module.exports = app;